%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\cp\Dysk Google\!STUDIA\PSM\P2\data.csv
%
% Auto-generated by MATLAB on 31-Mar-2021 12:04:31

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["n", "Mn"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
data = readtable("C:\Users\cp\Dysk Google\!STUDIA\PSM\P2\data.csv", opts);


%% Clear temporary variables
clear opts